import { execSync } from 'child_process';
import fs from 'fs';
import path from 'path';

console.log('=======================================================');
console.log('🚀 [Build] Hand Embroidered Dresses - Multan Store Build');
console.log('=======================================================');

// 1. Install frontend dependencies (ensure devDependencies like Vite are included)
console.log('\n📦 Step 1: Installing frontend dependencies...');
execSync('npm --prefix frontend install --include=dev', { stdio: 'inherit' });

// 2. Build Vite frontend
console.log('\n⚡ Step 2: Building Vite React frontend...');
execSync('npm --prefix frontend run build', { stdio: 'inherit' });

// 3. Ensure root dist directory exists and copy built frontend
const frontendDist = path.resolve('frontend/dist');
const rootDist = path.resolve('dist');

console.log('\n📂 Step 3: Preparing root distribution directory...');
if (!fs.existsSync(frontendDist)) {
  console.error('❌ Error: frontend/dist was not generated by Vite build!');
  process.exit(1);
}

if (!fs.existsSync(rootDist)) {
  fs.mkdirSync(rootDist, { recursive: true });
}

fs.cpSync(frontendDist, rootDist, { recursive: true });
console.log(`✅ Successfully copied ${frontendDist} -> ${rootDist}`);

// Verify index.html exists in root dist
const indexPath = path.join(rootDist, 'index.html');
if (fs.existsSync(indexPath)) {
  console.log('✅ Verified root dist/index.html is ready for Vercel deployment!');
} else {
  console.error('❌ Error: dist/index.html is missing!');
  process.exit(1);
}

console.log('\n🎉 [Build Complete] Store is ready for production live deployment!');
console.log('=======================================================');
